// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      /*case TargetPlatform.macOS:
        return macos;*/
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSInL45NBgaM5c0sN9ccdvJsqDj5ufMAg',
    appId: '1:1018091038707:web:721d96db9fc763170dd486',
    messagingSenderId: '1018091038707',
    projectId: 'lab4-4e141',
    authDomain: 'lab4-4e141.firebaseapp.com',
    storageBucket: 'lab4-4e141.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS21_VzhP3bk8BEhQVXK58tqRzgECMUxI',
    appId: '1:1018091038707:android:ae98175b440434110dd486',
    messagingSenderId: '1018091038707',
    projectId: 'lab4-4e141',
    storageBucket: 'lab4-4e141.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF4kPusemxcgSVNcYG0hx3NmAugDQBEaQ',
    appId: '1:1018091038707:ios:de2d7c7aef4082c30dd486',
    messagingSenderId: '1018091038707',
    projectId: 'lab4-4e141',
    storageBucket: 'lab4-4e141.appspot.com',
    iosBundleId: 'com.MIS.lab4.IOS',
  );

/*  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3ZW7bHz-jy7Y7RIfwT1RDnLnSEJlJNL0',
    appId: '1:620522314877:ios:74c13c86e4b0e17278e514',
    messagingSenderId: '620522314877',
    projectId: 'mis-lab-b6859',
    storageBucket: 'mis-lab-b6859.appspot.com',
    iosBundleId: 'mk.ukim.finki.mis.mis4.RunnerTests',
  );*/
}